/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, react-hooks/exhaustive-deps, react-hooks/preserve-manual-memoization, prefer-const, no-empty, no-useless-escape, no-prototype-builtins, @typescript-eslint/no-unsafe-function-type, @typescript-eslint/no-empty-object-type */
import { useState } from 'react';
import { Sparkles, BarChart3, MessageSquareText, RefreshCw, Loader2 } from 'lucide-react';

interface MissionAIProps {
  region: string;
  reportDays?: any[];
  onReportAutoGenerated?: (conclusion: string) => void;
}

export function MissionAI({ region, reportDays = [], onReportAutoGenerated }: MissionAIProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [estimate, setEstimate] = useState<any>(null);

  const handleGenerateWorkload = async () => {
    setIsGenerating(true);
    try {
      // Appel réel à l'API KPI pour récupérer les stats par zone/region
      const apiUrl = (import.meta as any).env?.VITE_API_URL || '/api';
      const res = await fetch(`${apiUrl}/kpi/summary`, { credentials: 'include' });
      if (!res.ok) throw new Error('API indisponible');
      const data = await res.json();

      // Calcul basé sur les vraies données
      const totalHouseholds =
        data.statusDistribution?.reduce((acc: number, s: any) => acc + Number(s._count), 0) ?? 0;
      const complexity =
        totalHouseholds > 1000 ? 'Élevée' : totalHouseholds > 500 ? 'Moyenne' : 'Basse';
      const days = Math.max(3, Math.ceil(totalHouseholds / 100));

      setEstimate({
        households: totalHouseholds,
        complexity,
        recommendation: `Organisation sur ${days} jours recommandée pour la région ${region} (${totalHouseholds} ménages actifs).`,
      });
    } catch {
      setEstimate({
        households: '—',
        complexity: 'Données indisponibles',
        recommendation:
          'Lancez une synchronisation Kobo pour obtenir les métriques réelles du terrain.',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleAutoGenerateConclusion = () => {
    setIsGenerating(true);
    // Génération basée sur les données réelles du journal (reportDays)
    const completedCount = reportDays.filter((d) => d.isCompleted).length;
    const totalCount = reportDays.length;
    const pct = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

    const conclusion = `La mission dans la région de ${region} s'est déroulée avec un taux d'exécution de ${pct}% (${completedCount}/${totalCount} journées validées). ${
      pct > 80
        ? 'Les objectifs principaux ont été atteints.'
        : pct > 50
          ? "L'avancement est en cours, des zones restantes à couvrir."
          : "Des difficultés ont limité l'avancement."
    } Recommandation : Suivi technique requis avant clôture officielle.`;

    onReportAutoGenerated?.(conclusion);
    setIsGenerating(false);
  };

  return (
    <section className="glass-card !p-8 !rounded-[2.5rem] space-y-8 bg-gradient-to-br from-white to-purple-50/30 dark:from-slate-900 dark:to-purple-900/10">
      <div className="flex items-center justify-between border-b border-purple-200/50 dark:border-purple-500/10 pb-6">
        <div>
          <h2 className="font-black text-slate-800 dark:text-white uppercase tracking-wider text-sm flex items-center gap-3">
            <div className="p-1.5 bg-purple-500/10 rounded-lg">
              <Sparkles size={16} className="text-purple-500" />
            </div>
            Intelligence Artificielle
          </h2>
          <p className="text-xs text-slate-500 font-bold uppercase tracking-widest mt-1 opacity-60">
            Optimisation et analyse prédictive
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Workload Estimator */}
        <div className="space-y-4 p-6 bg-slate-100/80 dark:bg-slate-800/40 rounded-3xl border border-purple-200/30 dark:border-purple-500/5">
          <div className="flex items-center gap-3 mb-2">
            <BarChart3 className="text-purple-500" size={18} />
            <h3 className="text-xs font-black uppercase tracking-widest text-slate-700 dark:text-slate-200">
              Estimateur de Charge
            </h3>
          </div>

          <button
            onClick={handleGenerateWorkload}
            disabled={isGenerating}
            className="w-full py-3 bg-purple-500 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-purple-600 transition-all flex items-center justify-center gap-2 shadow-lg shadow-purple-500/20 disabled:opacity-50"
          >
            {isGenerating ? (
              <Loader2 size={14} className="animate-spin" />
            ) : (
              <RefreshCw size={14} />
            )}
            Analyser la région {region}
          </button>

          {estimate && (
            <div className="mt-4 space-y-3 animate-in fade-in slide-in-from-bottom-2 duration-500">
              <div className="flex justify-between items-center text-xs font-bold uppercase">
                <span className="text-slate-400 tracking-wider">Ménages Potentiels</span>
                <span className="text-purple-600 dark:text-purple-400">{estimate.households}</span>
              </div>
              <div className="flex justify-between items-center text-xs font-bold uppercase">
                <span className="text-slate-400 tracking-wider">Complexité Terrain</span>
                <span className="text-purple-600 dark:text-purple-400">{estimate.complexity}</span>
              </div>
              <p className="p-3 bg-purple-500/5 rounded-xl text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium">
                <strong className="text-slate-700 dark:text-slate-200">Recommandation : </strong>
                {estimate.recommendation}
              </p>
            </div>
          )}
        </div>

        {/* Auto-Report Summary */}
        <div className="space-y-4 p-6 bg-slate-100/80 dark:bg-slate-800/40 rounded-3xl border border-purple-200/30 dark:border-purple-500/5">
          <div className="flex items-center gap-3 mb-2">
            <MessageSquareText className="text-indigo-500" size={18} />
            <h3 className="text-xs font-black uppercase tracking-widest text-slate-700 dark:text-slate-200">
              Générateur de Conclusion
            </h3>
          </div>

          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
            L'IA analyse le journal d'exécution pour rédiger automatiquement une synthèse
            professionnelle pour votre rapport.
          </p>

          <button
            onClick={handleAutoGenerateConclusion}
            disabled={isGenerating || reportDays.length === 0}
            className="w-full py-3 bg-indigo-500 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-indigo-600 transition-all flex items-center justify-center gap-2 shadow-lg shadow-indigo-500/20 disabled:opacity-50"
          >
            {isGenerating ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
            Générer la Conclusion Auto
          </button>

          {reportDays.length === 0 && (
            <p className="text-xs text-amber-500 font-bold uppercase tracking-wider text-center">
              Remplissez le journal d'exécution d'abord
            </p>
          )}
        </div>
      </div>
    </section>
  );
}
