/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { X, Users, Truck, Zap, Hammer, ChevronRight, Save, Wand2 } from 'lucide-react';
import { useLogistique } from '../../hooks/useLogistique';
import { useProject } from '../../contexts/ProjectContext';
import toast from 'react-hot-toast';
import apiClient from '../../api/client';
import {
  recommendTeamsForGrappe,
  type PlanningAllocationSource,
  normalizePlanningText,
} from '../../services/planningAllocation';
import type { Team } from '../../utils/types';

interface MapGrappeAllocationPanelProps {
  onClose: () => void;
  activeGrappeId: string;
  households: any[];
}

export const MapGrappeAllocationPanel: React.FC<MapGrappeAllocationPanelProps> = ({
  onClose,
  activeGrappeId,
  households,
}) => {
  const { teams, grappesConfig, refreshTeams } = useLogistique();
  const { project } = useProject();

  // Attempt to locate the exact Grappe from Backend config first, then Auto-generator
  const targetGrappe = useMemo(() => {
    if (!activeGrappeId) return null;
    const fromBackend = (grappesConfig as any)?.grappes?.find((g: any) => g.id === activeGrappeId);
    if (fromBackend) return fromBackend;

    // If not persisted yet (just generated by UI client worker)
    const hhInGrappe = households.filter(
      (h) => h.grappeId === activeGrappeId || String(h.id).includes(activeGrappeId)
    );
    return {
      id: activeGrappeId,
      nom: `Grappe Non Sauvegardée (${activeGrappeId.substring(0, 5)})`,
      region: hhInGrappe[0]?.region || 'Inconnue',
      householdsCount: hhInGrappe.length,
    };
  }, [activeGrappeId, grappesConfig, households]);

  // Available Teams categorized by trade
  const availableTeams = useMemo(() => {
    return (teams || []).filter((t) => t.status === 'active' || String(t.status) === 'disponible');
  }, [teams]);

  // Local State for selected teams in this panel before saving
  // Example: { "livreur": "uuid..", "macon": "uuid.." }
  const [selectedTeams, setSelectedTeams] = useState<Record<string, string>>({});
  const [recommendedSources, setRecommendedSources] = useState<
    Record<string, PlanningAllocationSource>
  >({});

  const handleAssign = (tradeKey: string, teamId: string) => {
    setSelectedTeams((prev) => ({ ...prev, [tradeKey]: teamId }));
    setRecommendedSources((prev) => ({ ...prev, [tradeKey]: teamId ? 'manual' : 'unassigned' }));
  };

  const handleSaveAllocation = async () => {
    if (Object.keys(selectedTeams).length === 0) {
      toast.error('Veuillez sélectionner au moins une équipe.');
      return;
    }

    if (!activeGrappeId) {
      toast.error("Aucune grappe sélectionnée pour l'affectation.");
      return;
    }

    const loading = toast.loading('Affectation des équipes sur le serveur...');
    try {
      await Promise.all(
        Object.values(selectedTeams).map((teamId) =>
          apiClient.post(`/teams/${teamId}/assign`, { grappeId: activeGrappeId })
        )
      );

      await refreshTeams();
      toast.dismiss(loading);
      toast.success('Équipes affectées avec succès !');
      onClose();
    } catch (error: any) {
      toast.dismiss(loading);
      const message =
        error?.response?.data?.error ||
        error?.message ||
        'Erreur lors de l’affectation des équipes.';
      toast.error(message);
    }
  };

  const handleAutoAllocate = () => {
    if (!targetGrappe) return;

    const isTradeMatch = (value: string | undefined, ...needles: string[]) => {
      const normalizedValue = normalizePlanningText(value);
      return needles.some((needle) => normalizedValue.includes(normalizePlanningText(needle)));
    };

    const recommendations = recommendTeamsForGrappe({
      teams: availableTeams as Team[],
      regionName: targetGrappe.region,
      projectConfig: project?.config,
      requirements: [
        {
          key: 'Livreur',
          matchTeam: (team) =>
            team.role === 'LOGISTICS' ||
            isTradeMatch(team.tradeKey, 'logistique', 'logistics') ||
            isTradeMatch(team.name, 'livr'),
        },
        {
          key: 'Maçon',
          matchTeam: (team) =>
            isTradeMatch(team.tradeKey, 'macons', 'maconnerie') ||
            isTradeMatch(team.name, 'macon', 'maçon'),
        },
        {
          key: 'Électricien',
          matchTeam: (team) =>
            isTradeMatch(team.tradeKey, 'reseau', 'interieur_type1') ||
            isTradeMatch(team.name, 'elec', 'reseau', 'réseau'),
        },
      ],
    });

    const nextSelection = Object.fromEntries(
      Object.entries(recommendations)
        .filter(([, decision]) => decision.team)
        .map(([tradeKey, decision]) => [tradeKey, decision.team!.id])
    );
    const nextSources = Object.fromEntries(
      Object.entries(recommendations).map(([tradeKey, decision]) => [tradeKey, decision.source])
    );

    setRecommendedSources(nextSources);

    if (Object.keys(nextSelection).length > 0) {
      setSelectedTeams(nextSelection);
      toast.success('Allocation canonique appliquée.');
    } else {
      toast.error("Aucune équipe éligible n'a pu être recommandée pour cette région.");
    }
  };

  if (!targetGrappe) return null;

  const renderTeamSelect = (label: string, icon: any, tradeKey: string) => {
    const Icon = icon;
    const source = recommendedSources[tradeKey];
    const sourceLabel =
      source === 'manual'
        ? 'Forcé'
        : source === 'configured'
          ? 'Config region'
          : source === 'balanced'
            ? 'Equilibre'
            : source === 'unassigned'
              ? 'Sans equipe'
              : null;

    return (
      <div className="flex flex-col gap-2 p-3 bg-slate-900 rounded-xl border border-slate-800 focus-within:border-indigo-500 transition-colors">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-slate-800 flex items-center justify-center text-slate-400">
              <Icon size={16} />
            </div>
            <span className="text-sm font-black text-slate-200 uppercase tracking-widest">
              {label}
            </span>
          </div>
          {sourceLabel ? (
            <span className="rounded-full border border-slate-700 bg-slate-950 px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.24em] text-slate-400">
              {sourceLabel}
            </span>
          ) : null}
        </div>
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-slate-800 flex items-center justify-center text-slate-400">
            <Icon size={16} />
          </div>
          <span className="text-xs font-semibold text-slate-500">
            Affectation terrain modifiable manuellement
          </span>
        </div>
        <select
          title={`Affectation ${label}`}
          className="w-full bg-slate-950 text-slate-300 text-sm p-3 rounded-lg border border-slate-700 outline-none focus:border-indigo-500 appearance-none"
          value={selectedTeams[tradeKey] || ''}
          onChange={(e) => handleAssign(tradeKey, e.target.value)}
        >
          <option value="">Sélectionner une équipe...</option>
          {availableTeams.map((t) => (
            <option key={t.id} value={t.id}>
              {t.name} • {t.capacity ? `${t.capacity} foyers/j` : 'Capacité non déf.'}
            </option>
          ))}
        </select>
      </div>
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 300 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 300 }}
      className="absolute left-3 right-3 top-auto bottom-[132px] z-[80] flex max-h-[calc(100dvh-11rem)] flex-col overflow-hidden rounded-3xl border border-slate-800/60 bg-slate-950/95 shadow-[0_0_50px_rgba(0,0,0,0.5)] backdrop-blur-3xl pointer-events-auto md:bottom-24 md:left-auto md:right-4 md:top-24 md:w-96 md:max-h-none"
    >
      <div className="p-4 sm:p-6 border-b border-slate-800/60 bg-gradient-to-b from-indigo-500/10 to-transparent flex justify-between items-start gap-3">
        <div>
          <div className="inline-flex px-3 py-1 bg-indigo-500/20 text-indigo-400 rounded-full text-[10px] font-black uppercase tracking-widest mb-3 border border-indigo-500/20">
            Affectation Multi-Métiers
          </div>
          <h3 className="text-xl font-bold text-white flex items-center gap-2">
            {targetGrappe.nom}
            <ChevronRight className="text-slate-600" size={18} />
          </h3>
          <p className="text-slate-400 text-xs mt-1 font-medium flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-500" />
            Région: {targetGrappe.region}
          </p>
        </div>
        <button
          onClick={onClose}
          title="Fermer le panneau"
          className="w-8 h-8 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
        >
          <X size={16} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 sm:p-6 flex flex-col gap-5 custom-scrollbar">
        <div className="p-4 rounded-xl bg-blue-500/5 items-start flex gap-3 text-sm text-blue-300 border border-blue-500/10">
          <Users size={18} className="shrink-0 mt-0.5" />
          <p>
            Déployez des équipes d'exécutants sur cette grappe pour leur donner accès via
            l'application Mobile.
          </p>
        </div>

        {renderTeamSelect('Livreur & Logistique', Truck, 'Livreur')}
        {renderTeamSelect('Installation & Maçonnerie', Hammer, 'Maçon')}
        {renderTeamSelect('Réseau & Électrification', Zap, 'Électricien')}
      </div>

      <div className="p-4 sm:p-5 border-t border-slate-800/60 bg-black/20 flex flex-col gap-3">
        <button
          onClick={handleAutoAllocate}
          className="w-full py-3.5 bg-slate-800/80 hover:bg-slate-800 text-indigo-400 rounded-2xl font-black transition-all flex items-center justify-center gap-2 border border-slate-700/50"
        >
          <Wand2 size={16} /> Allocation canonique
        </button>
        <button
          onClick={handleSaveAllocation}
          className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-black transition-all flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/25 active:scale-95"
        >
          <Save size={16} /> Enregistrer l'affectation
        </button>
      </div>
    </motion.div>
  );
};
