import React, { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { X, Users, Truck, Zap, Hammer, ChevronRight, Save, Wand2 } from 'lucide-react';
import { useLogistique } from '../../hooks/useLogistique';
import toast from 'react-hot-toast';

interface MapGrappeAllocationPanelProps {
    onClose: () => void;
    activeGrappeId: string;
    households: any[];
}

export const MapGrappeAllocationPanel: React.FC<MapGrappeAllocationPanelProps> = ({ onClose, activeGrappeId, households }) => {
    const { teams, grappesConfig } = useLogistique();
    
    // Attempt to locate the exact Grappe from Backend config first, then Auto-generator
    const targetGrappe = useMemo(() => {
        if (!activeGrappeId) return null;
        const fromBackend = grappesConfig?.grappes?.find((g: any) => g.id === activeGrappeId);
        if (fromBackend) return fromBackend;

        // If not persisted yet (just generated by UI client worker)
        const hhInGrappe = households.filter(h => h.grappeId === activeGrappeId || String(h.id).includes(activeGrappeId));
        return {
            id: activeGrappeId,
            nom: `Grappe Non Sauvegardée (${activeGrappeId.substring(0, 5)})`,
            region: hhInGrappe[0]?.region || 'Inconnue',
            householdsCount: hhInGrappe.length
        };
    }, [activeGrappeId, grappesConfig, households]);

    // Available Teams categorized by trade
    const availableTeams = useMemo(() => {
        return (teams || []).filter(t => t.status === 'active' || String(t.status) === 'disponible');
    }, [teams]);

    // Local State for selected teams in this panel before saving
    // Example: { "livreur": "uuid..", "macon": "uuid.." }
    const [selectedTeams, setSelectedTeams] = useState<Record<string, string>>({});

    const handleAssign = (tradeKey: string, teamId: string) => {
        setSelectedTeams(prev => ({ ...prev, [tradeKey]: teamId }));
    };

    const handleSaveAllocation = async () => {
        if (Object.keys(selectedTeams).length === 0) {
            toast.error("Veuillez sélectionner au moins une équipe.");
            return;
        }

        // TODO: In Phase 2/3, we will hook this up to the Backend `project_config.service` or a new `team_allocation.service`
        // For now, mock the success
        const loading = toast.loading("Affectation des équipes sur le serveur...");
        setTimeout(() => {
            toast.dismiss(loading);
            toast.success("Équipes affectées avec succès ! synchronisation en cours...");
            onClose();
        }, 1500);
    };

    const handleAutoAllocate = () => {
        // AI heuristic mocking for now: grab the first available of each trade in the same region
        if (!targetGrappe) return;
        const region = targetGrappe.region?.toLowerCase();
        
        let found = false;
        const autoMap: Record<string, string> = {};

        const findTeam = (role: string) => availableTeams.find(t => 
            String(t.role || '').toLowerCase() === role && 
            (String(t.region || '').toLowerCase() === region || !t.region)
        );

        const l = findTeam('logistics') || availableTeams.find(t => t.name.toLowerCase().includes('livr')); // Livreur
        const m = findTeam('installation') || availableTeams.find(t => t.name.toLowerCase().includes('maç')); // Maçon
        const e = findTeam('technical') || availableTeams.find(t => t.name.toLowerCase().includes('elec')); // Electricien
        
        if(l) { autoMap['Livreur'] = l.id; found = true; }
        if(m) { autoMap['Maçon'] = m.id; found = true; }
        if(e) { autoMap['Électricien'] = e.id; found = true; }

        if (found) {
            setSelectedTeams(autoMap);
            toast.success("Recommandation AI appliquée.");
        } else {
            toast.error("Aucune équipe rattachée à cette région n'a pu être trouvée par l'algorithme.");
        }
    };

    if (!targetGrappe) return null;

    const renderTeamSelect = (label: string, icon: any, tradeKey: string) => {
        const Icon = icon;
        return (
            <div className="flex flex-col gap-2 p-3 bg-slate-900 rounded-xl border border-slate-800 focus-within:border-indigo-500 transition-colors">
                <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-lg bg-slate-800 flex items-center justify-center text-slate-400">
                        <Icon size={16} />
                    </div>
                    <span className="text-sm font-black text-slate-200 uppercase tracking-widest">{label}</span>
                </div>
                <select 
                    title={`Affectation ${label}`}
                    className="w-full bg-slate-950 text-slate-300 text-sm p-3 rounded-lg border border-slate-700 outline-none focus:border-indigo-500 appearance-none"
                    value={selectedTeams[tradeKey] || ""}
                    onChange={(e) => handleAssign(tradeKey, e.target.value)}
                >
                    <option value="">Sélectionner une équipe...</option>
                    {availableTeams.map(t => (
                        <option key={t.id} value={t.id}>{t.name} • {t.capacity ? `${t.capacity} foyers/j` : 'Capacité non déf.'}</option>
                    ))}
                </select>
            </div>
        );
    }

    return (
        <motion.div
            initial={{ opacity: 0, x: 300 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 300 }}
            className="absolute right-4 top-24 bottom-24 w-96 bg-slate-950/95 backdrop-blur-3xl border border-slate-800/60 rounded-3xl overflow-hidden shadow-[0_0_50px_rgba(0,0,0,0.5)] flex flex-col z-[80] pointer-events-auto"
        >
            <div className="p-6 border-b border-slate-800/60 bg-gradient-to-b from-indigo-500/10 to-transparent flex justify-between items-start">
                <div>
                    <div className="inline-flex px-3 py-1 bg-indigo-500/20 text-indigo-400 rounded-full text-[10px] font-black uppercase tracking-widest mb-3 border border-indigo-500/20">
                        Affectation Multi-Métiers
                    </div>
                    <h3 className="text-xl font-bold text-white flex items-center gap-2">
                        {targetGrappe.nom}
                        <ChevronRight className="text-slate-600" size={18} />
                    </h3>
                    <p className="text-slate-400 text-xs mt-1 font-medium flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded-full bg-emerald-500" />
                        Région: {targetGrappe.region}
                    </p>
                </div>
                <button
                    onClick={onClose}
                    title="Fermer le panneau"
                    className="w-8 h-8 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
                >
                    <X size={16} />
                </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-5 custom-scrollbar">
                
                <div className="p-4 rounded-xl bg-blue-500/5 items-start flex gap-3 text-sm text-blue-300 border border-blue-500/10">
                    <Users size={18} className="shrink-0 mt-0.5" />
                    <p>Déployez des équipes d'exécutants sur cette grappe pour leur donner accès via l'application Mobile.</p>
                </div>

                {renderTeamSelect("Livreur & Logistique", Truck, "Livreur")}
                {renderTeamSelect("Installation & Maçonnerie", Hammer, "Maçon")}
                {renderTeamSelect("Réseau & Électrification", Zap, "Électricien")}

            </div>

            <div className="p-5 border-t border-slate-800/60 bg-black/20 flex flex-col gap-3">
                <button 
                    onClick={handleAutoAllocate}
                    className="w-full py-3.5 bg-slate-800/80 hover:bg-slate-800 text-indigo-400 rounded-2xl font-black transition-all flex items-center justify-center gap-2 border border-slate-700/50"
                >
                    <Wand2 size={16} /> Allocation IA (Recommandation)
                </button>
                <button 
                    onClick={handleSaveAllocation}
                    className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-black transition-all flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/25 active:scale-95"
                >
                    <Save size={16} /> Enregistrer l'affectation
                </button>
            </div>
        </motion.div>
    );
};
