/**
 * Frontend Module Registry - GED OS Master Hub
 *
 * Ce fichier est la source unique de vérité pour TOUS les modules et pages de l'application.
 * Il pilote :
 * 1. La Sidebar (Navigation)
 * 2. Le Routage dynamique (App.tsx)
 * 3. La création de projet (AdminProjectCreation.tsx)
 */

import { lazyWithRetry } from '../utils/lazy';
import { PERMISSIONS, ROLES } from '../utils/security/types';

/** Permission requise : une chaîne OU un tableau (OR logique) */
export type ModuleRequiredPermission = string | readonly string[];

export type ModuleRegistryEntry = {
  key: string;
  name: string;
  icon: string;
  component: any;
  route: string;
  requiredPermission?: ModuleRequiredPermission;
  allowedRoles?: string[];
  required?: boolean;
  description: string;
  category: 'PILOTAGE' | 'OPÉRATIONS' | 'SYSTÈME' | 'UTILITAIRE';
  visible?: (context: any) => boolean;
  noLayout?: boolean; // Si vrai, ne pas afficher le Layout (ex: Login)
  tags?: string[];
  isPackage?: boolean; // Si vrai, apparaît dans le Hub de gestion des modules
  packageCategory?: 'core' | 'advanced' | 'experimental' | 'admin';
  global?: boolean; // Si true, l'admin peut activer/désactiver globalement
};

export const MODULE_REGISTRY: Record<string, ModuleRegistryEntry> = {
  // --- 📦 PILOTAGE ---
  home: {
    key: 'home',
    name: 'Accueil',
    icon: 'Home',
    component: lazyWithRetry(() => import('../pages/Home'), 'lazy:home'),
    route: '/home',
    category: 'PILOTAGE',
    description: 'Retour à la sélection des projets',
  },
  dashboard: {
    key: 'dashboard',
    name: 'Tableau de Bord',
    icon: 'LayoutDashboard',
    component: lazyWithRetry(() => import('../pages/Dashboard'), 'lazy:dashboard'),
    route: '/dashboard',
    requiredPermission: PERMISSIONS.UI_PROJECTS,
    required: true,
    category: 'PILOTAGE',
    description: "Vue d'ensemble de la mission et indicateurs clés",
    tags: ['IA'],
    isPackage: true,
    packageCategory: 'core',
    global: false,
  },
  simulation: {
    key: 'simulation',
    name: 'Simulation',
    icon: 'Calculator',
    component: lazyWithRetry(() => import('../pages/Simulation'), 'lazy:simulation'),
    route: '/simulation',
    requiredPermission: PERMISSIONS.IA_SIMULATION,
    category: 'PILOTAGE',
    description: 'Calculez vos budgets et simulez des scénarios financiers',
    tags: ['IA'],
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  charges: {
    key: 'charges',
    name: 'Charge',
    icon: 'BarChart3',
    component: lazyWithRetry(() => import('../pages/Charges'), 'lazy:charges'),
    route: '/charges',
    allowedRoles: [ROLES.ADMIN, ROLES.DIRECTEUR, ROLES.COMPTABLE],
    category: 'PILOTAGE',
    description: 'Renseignez les budgets prévus, coûts réels et écarts financiers',
    visible: (ctx) => ctx.canAccessCharges,
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  bordereau: {
    key: 'bordereau',
    name: 'Bordereau',
    icon: 'Users',
    component: lazyWithRetry(() => import('../pages/Bordereau'), 'lazy:bordereau'),
    route: '/bordereau',
    requiredPermission: PERMISSIONS.LOGISTIQUE_OM,
    category: 'PILOTAGE',
    description: 'Gérez la logistique des équipes et les affectations terrain',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  cahier: {
    key: 'cahier',
    name: 'Cahier de Charge',
    icon: 'FileText',
    component: lazyWithRetry(() => import('../pages/Cahier'), 'lazy:cahier'),
    route: '/cahier',
    requiredPermission: [PERMISSIONS.TERRAIN_READ, PERMISSIONS.FINANCE_READ],
    category: 'PILOTAGE',
    description: 'Consultez les spécifications techniques et les rapports détaillés',
  },
  sharedoc: {
    key: 'sharedoc',
    name: 'Documents Partagés',
    icon: 'Folder',
    component: lazyWithRetry(() => import('../pages/Sharedoc'), 'lazy:sharedoc'),
    route: '/sharedoc',
    requiredPermission: [PERMISSIONS.DOCS_PV],
    category: 'PILOTAGE',
    description: 'Gérez les documents, dossiers et versions partagés',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  pv_automation: {
    key: 'pv_automation',
    name: 'Automatisation PV',
    icon: 'ShieldCheck',
    component: lazyWithRetry(() => import('../pages/PVAutomation'), 'lazy:pv-automation'),
    route: '/admin/pv-automation',
    requiredPermission: PERMISSIONS.DOCS_PV,
    category: 'PILOTAGE',
    description: 'Générez et gérez les procès-verbaux automatiquement',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },

  // --- 🏗️ OPÉRATIONS ---
  terrain: {
    key: 'terrain',
    name: 'Terrain',
    icon: 'Map',
    component: lazyWithRetry(() => import('../pages/Terrain'), 'lazy:terrain'),
    route: '/terrain',
    requiredPermission: PERMISSIONS.UI_MAP,
    category: 'OPÉRATIONS',
    description: 'Suivez les entités sur la carte interactive en temps réel',
    tags: ['Offline', 'SIG'],
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  communication: {
    key: 'communication',
    name: 'Communication',
    icon: 'MessagesSquare',
    component: lazyWithRetry(() => import('../pages/Communication'), 'lazy:communication'),
    route: '/communication',
    category: 'OPÉRATIONS',
    description: 'Messagerie équipe en direct, salons communs et discussions privées',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  planning: {
    key: 'planning',
    name: 'Planning',
    icon: 'Calendar',
    component: lazyWithRetry(() => import('../pages/Planning'), 'lazy:planning'),
    route: '/planning',
    requiredPermission: PERMISSIONS.MISSIONS_PLANNING,
    category: 'OPÉRATIONS',
    description: 'Planification intelligente des travaux par équipe',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  formation: {
    key: 'formation',
    name: 'Formations',
    icon: 'GraduationCap',
    component: lazyWithRetry(() => import('../pages/PlanningFormation'), 'lazy:planning-formation'),
    route: '/planning-formation',
    requiredPermission: PERMISSIONS.UI_MAP,
    category: 'OPÉRATIONS',
    description: 'Planification des formations par région et session',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  logistique: {
    key: 'logistique',
    name: 'Logistique',
    icon: 'Truck',
    component: lazyWithRetry(() => import('../pages/Logistique'), 'lazy:logistique'),
    route: '/logistique',
    requiredPermission: PERMISSIONS.LOGISTIQUE_MANAGE,
    category: 'OPÉRATIONS',
    description: 'Gestion du déploiement et des ressources matérielles',
    tags: ['QR'],
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  atelier: {
    key: 'atelier',
    name: 'Atelier',
    icon: 'LayoutGrid',
    component: lazyWithRetry(() => import('../pages/Atelier'), 'lazy:atelier'),
    route: '/atelier',
    requiredPermission: PERMISSIONS.LOGISTIQUE_ATELIER,
    category: 'OPÉRATIONS',
    description: 'Saisie et journalisation de la préparation des kits',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  approval: {
    key: 'approval',
    name: 'Approbation',
    icon: 'ShieldCheck',
    component: lazyWithRetry(() => import('../pages/Approbation'), 'lazy:approbation'),
    route: '/admin/approval',
    requiredPermission: PERMISSIONS.MISSIONS_VALIDATE,
    category: 'OPÉRATIONS',
    description: 'Validez ou rejetez les interventions effectuées sur le terrain',
    isPackage: true,
    packageCategory: 'advanced',
    global: true,
  },
  mission: {
    key: 'mission',
    name: 'Missions',
    icon: 'ClipboardList',
    component: lazyWithRetry(() => import('../pages/MissionOrder'), 'lazy:mission-order'),
    route: '/admin/mission',
    requiredPermission: PERMISSIONS.MISSIONS_CREATE,
    category: 'OPÉRATIONS',
    description: 'Planifiez vos prochaines missions et objectifs',
    visible: (ctx) => (ctx.nRole === 'DIRECTEUR' ? ctx.visibleMissionPanels.length > 0 : true),
    isPackage: true,
    packageCategory: 'core',
    global: false,
  },

  // --- ⚙️ SYSTÈME ---
  modules: {
    key: 'modules',
    name: 'Centre de Contrôle',
    icon: 'ServerCog',
    component: lazyWithRetry(() => import('../pages/AdminModules'), 'lazy:admin-modules'),
    route: '/admin/hub',
    requiredPermission: PERMISSIONS.SYSTEM_CONFIG,
    category: 'SYSTÈME',
    description: 'Tableau de bord de configuration globale et modules système',
  },
  users: {
    key: 'users',
    name: 'Utilisateurs',
    icon: 'Users',
    component: lazyWithRetry(() => import('../pages/AdminUsers'), 'lazy:admin-users'),
    route: '/admin/users',
    requiredPermission: PERMISSIONS.SYSTEM_USERS,
    category: 'SYSTÈME',
    description: 'Gérez les comptes, les rôles et les accès de votre équipe',
  },
  diagnostic: {
    key: 'diagnostic',
    name: 'Diagnostic Santé',
    icon: 'Activity',
    component: lazyWithRetry(() => import('../pages/DiagnosticSante'), 'lazy:diagnostic'),
    route: '/admin/diagnostic',
    requiredPermission: PERMISSIONS.SYSTEM_AUDIT,
    category: 'SYSTÈME',
    description: 'Vérifiez l’état technique du serveur et de la synchronisation',
  },
  kobo_terminal: {
    key: 'kobo_terminal',
    name: 'Terminal KoboToolbox',
    icon: 'Terminal',
    component: lazyWithRetry(() => import('../pages/DashboardViews/KoboTerminal'), 'lazy:kobo-terminal'),
    route: '/admin/kobo-terminal',
    requiredPermission: PERMISSIONS.TERRAIN_TERMINAL,
    category: 'SYSTÈME',
    description: 'API officielle KoboCollect pour la synchronisation',
    isPackage: true,
    packageCategory: 'admin',
    global: true,
  },
  ged_os_toolbox: {
    key: 'ged_os_toolbox',
    name: 'GED OS Toolbox',
    icon: 'ClipboardCheck',
    component: lazyWithRetry(() => import('../pages/InternalKoboSubmissions'), 'lazy:internal-kobo-submissions'),
    route: '/admin/internal-kobo',
    requiredPermission: PERMISSIONS.TERRAIN_TERMINAL,
    category: 'SYSTÈME',
    description: 'GED OS Toolbox - Fiches terrain natives soumises directement au VPS',
    isPackage: true,
    packageCategory: 'admin',
    global: true,
  },
  ged_os_collect: {
    key: 'ged_os_collect',
    name: 'GED OS Collect',
    icon: 'Activity',
    component: lazyWithRetry(() => import('../pages/GedOsCollect'), 'lazy:ged-os-collect'),
    route: '/admin/ged-os-collect',
    requiredPermission: PERMISSIONS.UI_MAP,
    category: 'SYSTÈME',
    description: 'GED OS Collect - Moteur de saisie terrain universel GED OS',
  },
  organization: {
    key: 'organization',
    name: 'Organisation',
    icon: 'Building2',
    component: lazyWithRetry(() => import('../pages/OrganizationSettings'), 'lazy:organization'),
    route: '/admin/organization',
    requiredPermission: PERMISSIONS.SYSTEM_CONFIG,
    category: 'SYSTÈME',
    description: 'Configurez votre identité visuelle et les paramètres de structure',
  },
  settings: {
    key: 'settings',
    name: 'Paramètres',
    icon: 'Settings',
    component: lazyWithRetry(() => import('../pages/Settings'), 'lazy:settings'),
    route: '/settings',
    requiredPermission: PERMISSIONS.SYSTEM_CONFIG,
    category: 'SYSTÈME',
    description: 'Réglages globaux de l’application et préférences personnelles',
  },
  security: {
    key: 'security',
    name: 'Sécurité',
    icon: 'ShieldCheck',
    component: lazyWithRetry(() => import('../pages/SecuritySettings'), 'lazy:security'),
    route: '/admin/security',
    requiredPermission: PERMISSIONS.SYSTEM_CONFIG,
    category: 'SYSTÈME',
    description: "Journal d'audit et contrôles de sécurité avancés",
  },
  ai_config: {
    key: 'ai_config',
    name: 'Configuration IA',
    icon: 'Brain',
    component: lazyWithRetry(() => import('../pages/AdminAIConfig'), 'lazy:admin-ai-config'),
    route: '/admin/ai-config',
    requiredPermission: PERMISSIONS.IA_CONFIG,
    category: 'SYSTÈME',
    description: 'Configuration du cerveau IA, modes et auto-entraînement souverain',
    isPackage: true,
    packageCategory: 'admin',
    global: false,
  },
  kobo_mapping: {
    key: 'kobo_mapping',
    name: 'Mapping Kobo',
    icon: 'RefreshCw',
    component: lazyWithRetry(() => import('../pages/KoboMappingMaster'), 'lazy:kobo-mapping'),
    route: '/admin/kobo-mapping',
    requiredPermission: PERMISSIONS.SYSTEM_CONFIG,
    category: 'SYSTÈME',
    description: 'Configuration avancée des correspondances de champs KoboToolbox',
  },
  project_creation: {
    key: 'project_creation',
    name: 'Création Projet',
    icon: 'LayoutGrid',
    component: lazyWithRetry(() => import('../pages/AdminProjectCreation'), 'lazy:admin-project-creation'),
    route: '/admin/project-creation',
    requiredPermission: PERMISSIONS.SYSTEM_CONFIG,
    category: 'SYSTÈME',
    description: 'Initialisation de nouveaux projets et templates',
  },
  help: {
    key: 'help',
    name: "Centre d'Aide",
    icon: 'HelpCircle',
    component: lazyWithRetry(() => import('../pages/Aide'), 'lazy:aide'),
    route: '/aide',
    category: 'SYSTÈME',
    description: "Besoin d'un guide ? Consultez notre documentation complète",
  },

  // --- 🛠️ UTILITAIRE (No Layout) ---
  login: {
    key: 'login',
    name: 'Connexion',
    icon: 'LogIn',
    component: lazyWithRetry(() => import('../pages/Login'), 'lazy:login'),
    route: '/login',
    category: 'UTILITAIRE',
    description: 'Accès sécurisé à la plateforme',
    noLayout: true,
  },
  mission_verification: {
    key: 'mission_verification',
    name: 'Vérification Mission',
    icon: 'Search',
    component: lazyWithRetry(() => import('../pages/MissionVerification'), 'lazy:mission-verification'),
    route: '/verify/mission/:identifier',
    category: 'UTILITAIRE',
    description: 'Vérification publique des ordres de mission',
    noLayout: true,
  },
};

export const getAllModules = () => Object.values(MODULE_REGISTRY);
export const getModule = (key: string) => MODULE_REGISTRY[key] || null;
