/**
 * grappes-config.js — Configuration géographique du projet
 * Ce fichier est GÉNÉRÉ AUTOMATIQUEMENT par create_sous_grappes.py
 * 
 * Rubriques :
 *   - grappes      : Regroupements macro par GPS (K-Means)
 *   - sous_grappes : Secteurs d'intervention par équipe (division des grappes)
 */
export const GRAPPES_CONFIG = {
  "grappes": [
    {
      "id": "kaffrine_grappe_1",
      "nom": "Kaffrine – Grappe 1",
      "region": "Kaffrine",
      "numero": 1,
      "nb_menages": 722,
      "centroide_lat": 14.189357,
      "centroide_lon": -15.438856,
      "rayon_moyen_km": 3.5,
      "rayon_max_km": 7.05,
      "sous_grappes": []
    },
    {
      "id": "kaffrine_grappe_2",
      "nom": "Kaffrine – Grappe 2",
      "region": "Kaffrine",
      "numero": 2,
      "nb_menages": 617,
      "centroide_lat": 14.230624,
      "centroide_lon": -15.309393,
      "rayon_moyen_km": 4.38,
      "rayon_max_km": 8.97,
      "sous_grappes": []
    },
    {
      "id": "kaffrine_grappe_3",
      "nom": "Kaffrine – Grappe 3",
      "region": "Kaffrine",
      "numero": 3,
      "nb_menages": 562,
      "centroide_lat": 14.155395,
      "centroide_lon": -15.546118,
      "rayon_moyen_km": 5.16,
      "rayon_max_km": 6.51,
      "sous_grappes": []
    },
    {
      "id": "kaffrine_grappe_4",
      "nom": "Kaffrine – Grappe 4",
      "region": "Kaffrine",
      "numero": 4,
      "nb_menages": 283,
      "centroide_lat": 14.387435,
      "centroide_lon": -15.24757,
      "rayon_moyen_km": 6.03,
      "rayon_max_km": 48.85,
      "sous_grappes": []
    },
    {
      "id": "tambacounda_grappe_1",
      "nom": "Tambacounda – Grappe 1",
      "region": "Tambacounda",
      "numero": 1,
      "nb_menages": 733,
      "centroide_lat": 13.342713,
      "centroide_lon": -13.620338,
      "rayon_moyen_km": 4.85,
      "rayon_max_km": 8.42,
      "sous_grappes": []
    },
    {
      "id": "tambacounda_grappe_2",
      "nom": "Tambacounda – Grappe 2",
      "region": "Tambacounda",
      "numero": 2,
      "nb_menages": 618,
      "centroide_lat": 13.423247,
      "centroide_lon": -13.702384,
      "rayon_moyen_km": 4.79,
      "rayon_max_km": 8.21,
      "sous_grappes": []
    }
  ],
  "sous_grappes": [
    {
      "id": "KAF-G1-SG01",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 1,
      "nom": "Kaffrine – Grappe 1 – SG01",
      "code": "KAF-G1-SG01",
      "nb_menages": 219,
      "equipe_affectee": "Éq.Int-01",
      "centroide_lat": 14.194082,
      "centroide_lon": -15.475078
    },
    {
      "id": "KAF-G1-SG02",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 2,
      "nom": "Kaffrine – Grappe 1 – SG02",
      "code": "KAF-G1-SG02",
      "nb_menages": 126,
      "equipe_affectee": "Éq.Int-02",
      "centroide_lat": 14.199349,
      "centroide_lon": -15.405812
    },
    {
      "id": "KAF-G1-SG03",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 3,
      "nom": "Kaffrine – Grappe 1 – SG03",
      "code": "KAF-G1-SG03",
      "nb_menages": 99,
      "equipe_affectee": "Éq.Int-03",
      "centroide_lat": 14.174934,
      "centroide_lon": -15.459871
    },
    {
      "id": "KAF-G1-SG04",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 4,
      "nom": "Kaffrine – Grappe 1 – SG04",
      "code": "KAF-G1-SG04",
      "nb_menages": 82,
      "equipe_affectee": "Éq.Int-04",
      "centroide_lat": 14.186712,
      "centroide_lon": -15.436513
    },
    {
      "id": "KAF-G1-SG05",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 5,
      "nom": "Kaffrine – Grappe 1 – SG05",
      "code": "KAF-G1-SG05",
      "nb_menages": 74,
      "equipe_affectee": "Éq.Int-05",
      "centroide_lat": 14.213473,
      "centroide_lon": -15.383837
    },
    {
      "id": "KAF-G1-SG06",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 6,
      "nom": "Kaffrine – Grappe 1 – SG06",
      "code": "KAF-G1-SG06",
      "nb_menages": 44,
      "equipe_affectee": "Éq.Int-06",
      "centroide_lat": 14.166218,
      "centroide_lon": -15.416722
    },
    {
      "id": "KAF-G1-SG07",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 7,
      "nom": "Kaffrine – Grappe 1 – SG07",
      "code": "KAF-G1-SG07",
      "nb_menages": 39,
      "equipe_affectee": "Éq.Int-07",
      "centroide_lat": 14.198041,
      "centroide_lon": -15.438636
    },
    {
      "id": "KAF-G1-SG08",
      "grappe_id": "KAF-G1",
      "region": "Kaffrine",
      "grappe_numero": 1,
      "sous_grappe_numero": 8,
      "nom": "Kaffrine – Grappe 1 – SG08",
      "code": "KAF-G1-SG08",
      "nb_menages": 39,
      "equipe_affectee": "Éq.Int-08",
      "centroide_lat": 14.14437,
      "centroide_lon": -15.423383
    },
    {
      "id": "KAF-G2-SG01",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 1,
      "nom": "Kaffrine – Grappe 2 – SG01",
      "code": "KAF-G2-SG01",
      "nb_menages": 197,
      "equipe_affectee": "Éq.Int-09",
      "centroide_lat": 14.188502,
      "centroide_lon": -15.298243
    },
    {
      "id": "KAF-G2-SG02",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 2,
      "nom": "Kaffrine – Grappe 2 – SG02",
      "code": "KAF-G2-SG02",
      "nb_menages": 126,
      "equipe_affectee": "Éq.Int-10",
      "centroide_lat": 14.234793,
      "centroide_lon": -15.339566
    },
    {
      "id": "KAF-G2-SG03",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 3,
      "nom": "Kaffrine – Grappe 2 – SG03",
      "code": "KAF-G2-SG03",
      "nb_menages": 90,
      "equipe_affectee": "Éq.Int-11",
      "centroide_lat": 14.239003,
      "centroide_lon": -15.302786
    },
    {
      "id": "KAF-G2-SG04",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 4,
      "nom": "Kaffrine – Grappe 2 – SG04",
      "code": "KAF-G2-SG04",
      "nb_menages": 84,
      "equipe_affectee": "Éq.Int-12",
      "centroide_lat": 14.300013,
      "centroide_lon": -15.290194
    },
    {
      "id": "KAF-G2-SG05",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 5,
      "nom": "Kaffrine – Grappe 2 – SG05",
      "code": "KAF-G2-SG05",
      "nb_menages": 41,
      "equipe_affectee": "Éq.Int-13",
      "centroide_lat": 14.25702,
      "centroide_lon": -15.32105
    },
    {
      "id": "KAF-G2-SG06",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 6,
      "nom": "Kaffrine – Grappe 2 – SG06",
      "code": "KAF-G2-SG06",
      "nb_menages": 40,
      "equipe_affectee": "Éq.Int-14",
      "centroide_lat": 14.25176,
      "centroide_lon": -15.270954
    },
    {
      "id": "KAF-G2-SG07",
      "grappe_id": "KAF-G2",
      "region": "Kaffrine",
      "grappe_numero": 2,
      "sous_grappe_numero": 7,
      "nom": "Kaffrine – Grappe 2 – SG07",
      "code": "KAF-G2-SG07",
      "nb_menages": 39,
      "equipe_affectee": "Éq.Int-15",
      "centroide_lat": 14.211706,
      "centroide_lon": -15.352008
    },
    {
      "id": "KAF-G3-SG01",
      "grappe_id": "KAF-G3",
      "region": "Kaffrine",
      "grappe_numero": 3,
      "sous_grappe_numero": 1,
      "nom": "Kaffrine – Grappe 3 – SG01",
      "code": "KAF-G3-SG01",
      "nb_menages": 245,
      "equipe_affectee": "Éq.Int-16",
      "centroide_lat": 14.140857,
      "centroide_lon": -15.596898
    },
    {
      "id": "KAF-G3-SG02",
      "grappe_id": "KAF-G3",
      "region": "Kaffrine",
      "grappe_numero": 3,
      "sous_grappe_numero": 2,
      "nom": "Kaffrine – Grappe 3 – SG02",
      "code": "KAF-G3-SG02",
      "nb_menages": 189,
      "equipe_affectee": "Éq.Int-17",
      "centroide_lat": 14.174345,
      "centroide_lon": -15.498434
    },
    {
      "id": "KAF-G3-SG03",
      "grappe_id": "KAF-G3",
      "region": "Kaffrine",
      "grappe_numero": 3,
      "sous_grappe_numero": 3,
      "nom": "Kaffrine – Grappe 3 – SG03",
      "code": "KAF-G3-SG03",
      "nb_menages": 41,
      "equipe_affectee": "Éq.Int-18",
      "centroide_lat": 14.172565,
      "centroide_lon": -15.52592
    },
    {
      "id": "KAF-G3-SG04",
      "grappe_id": "KAF-G3",
      "region": "Kaffrine",
      "grappe_numero": 3,
      "sous_grappe_numero": 4,
      "nom": "Kaffrine – Grappe 3 – SG04",
      "code": "KAF-G3-SG04",
      "nb_menages": 40,
      "equipe_affectee": "Éq.Int-19",
      "centroide_lat": 14.139544,
      "centroide_lon": -15.505261
    },
    {
      "id": "KAF-G3-SG05",
      "grappe_id": "KAF-G3",
      "region": "Kaffrine",
      "grappe_numero": 3,
      "sous_grappe_numero": 5,
      "nom": "Kaffrine – Grappe 3 – SG05",
      "code": "KAF-G3-SG05",
      "nb_menages": 38,
      "equipe_affectee": "Éq.Int-20",
      "centroide_lat": 14.158054,
      "centroide_lon": -15.519473
    },
    {
      "id": "KAF-G3-SG06",
      "grappe_id": "KAF-G3",
      "region": "Kaffrine",
      "grappe_numero": 3,
      "sous_grappe_numero": 6,
      "nom": "Kaffrine – Grappe 3 – SG06",
      "code": "KAF-G3-SG06",
      "nb_menages": 9,
      "equipe_affectee": "Éq.Int-21",
      "centroide_lat": 14.134209,
      "centroide_lon": -15.551246
    },
    {
      "id": "KAF-G4-SG01",
      "grappe_id": "KAF-G4",
      "region": "Kaffrine",
      "grappe_numero": 4,
      "sous_grappe_numero": 1,
      "nom": "Kaffrine – Grappe 4 – SG01",
      "code": "KAF-G4-SG01",
      "nb_menages": 126,
      "equipe_affectee": "Éq.Int-22",
      "centroide_lat": 14.431164,
      "centroide_lon": -15.226316
    },
    {
      "id": "KAF-G4-SG02",
      "grappe_id": "KAF-G4",
      "region": "Kaffrine",
      "grappe_numero": 4,
      "sous_grappe_numero": 2,
      "nom": "Kaffrine – Grappe 4 – SG02",
      "code": "KAF-G4-SG02",
      "nb_menages": 102,
      "equipe_affectee": "Éq.Int-23",
      "centroide_lat": 14.359898,
      "centroide_lon": -15.280757
    },
    {
      "id": "KAF-G4-SG03",
      "grappe_id": "KAF-G4",
      "region": "Kaffrine",
      "grappe_numero": 4,
      "sous_grappe_numero": 3,
      "nom": "Kaffrine – Grappe 4 – SG03",
      "code": "KAF-G4-SG03",
      "nb_menages": 54,
      "equipe_affectee": "Éq.Int-24",
      "centroide_lat": 14.33295,
      "centroide_lon": -15.22745
    },
    {
      "id": "KAF-G4-SG04",
      "grappe_id": "KAF-G4",
      "region": "Kaffrine",
      "grappe_numero": 4,
      "sous_grappe_numero": 4,
      "nom": "Kaffrine – Grappe 4 – SG04",
      "code": "KAF-G4-SG04",
      "nb_menages": 1,
      "equipe_affectee": "Éq.Int-25",
      "centroide_lat": 14.62859,
      "centroide_lon": -15.62688
    },
    {
      "id": "TAM-G1-SG01",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 1,
      "nom": "Tambacounda – Grappe 1 – SG01",
      "code": "TAM-G1-SG01",
      "nb_menages": 127,
      "equipe_affectee": "Éq.Int-01",
      "centroide_lat": 13.366926,
      "centroide_lon": -13.6442
    },
    {
      "id": "TAM-G1-SG02",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 2,
      "nom": "Tambacounda – Grappe 1 – SG02",
      "code": "TAM-G1-SG02",
      "nb_menages": 124,
      "equipe_affectee": "Éq.Int-02",
      "centroide_lat": 13.317226,
      "centroide_lon": -13.565339
    },
    {
      "id": "TAM-G1-SG03",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 3,
      "nom": "Tambacounda – Grappe 1 – SG03",
      "code": "TAM-G1-SG03",
      "nb_menages": 121,
      "equipe_affectee": "Éq.Int-03",
      "centroide_lat": 13.344676,
      "centroide_lon": -13.679893
    },
    {
      "id": "TAM-G1-SG04",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 4,
      "nom": "Tambacounda – Grappe 1 – SG04",
      "code": "TAM-G1-SG04",
      "nb_menages": 99,
      "equipe_affectee": "Éq.Int-04",
      "centroide_lat": 13.338893,
      "centroide_lon": -13.617658
    },
    {
      "id": "TAM-G1-SG05",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 5,
      "nom": "Tambacounda – Grappe 1 – SG05",
      "code": "TAM-G1-SG05",
      "nb_menages": 92,
      "equipe_affectee": "Éq.Int-05",
      "centroide_lat": 13.354339,
      "centroide_lon": -13.668987
    },
    {
      "id": "TAM-G1-SG06",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 6,
      "nom": "Tambacounda – Grappe 1 – SG06",
      "code": "TAM-G1-SG06",
      "nb_menages": 81,
      "equipe_affectee": "Éq.Int-06",
      "centroide_lat": 13.321683,
      "centroide_lon": -13.567049
    },
    {
      "id": "TAM-G1-SG07",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 7,
      "nom": "Tambacounda – Grappe 1 – SG07",
      "code": "TAM-G1-SG07",
      "nb_menages": 52,
      "equipe_affectee": "Éq.Int-07",
      "centroide_lat": 13.338664,
      "centroide_lon": -13.572075
    },
    {
      "id": "TAM-G1-SG08",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 8,
      "nom": "Tambacounda – Grappe 1 – SG08",
      "code": "TAM-G1-SG08",
      "nb_menages": 25,
      "equipe_affectee": "Éq.Int-08",
      "centroide_lat": 13.377516,
      "centroide_lon": -13.605325
    },
    {
      "id": "TAM-G1-SG09",
      "grappe_id": "TAM-G1",
      "region": "Tambacounda",
      "grappe_numero": 1,
      "sous_grappe_numero": 9,
      "nom": "Tambacounda – Grappe 1 – SG09",
      "code": "TAM-G1-SG09",
      "nb_menages": 12,
      "equipe_affectee": "Éq.Int-09",
      "centroide_lat": 13.359416,
      "centroide_lon": -13.584887
    },
    {
      "id": "TAM-G2-SG01",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 1,
      "nom": "Tambacounda – Grappe 2 – SG01",
      "code": "TAM-G2-SG01",
      "nb_menages": 177,
      "equipe_affectee": "Éq.Int-10",
      "centroide_lat": 13.385488,
      "centroide_lon": -13.739794
    },
    {
      "id": "TAM-G2-SG02",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 2,
      "nom": "Tambacounda – Grappe 2 – SG02",
      "code": "TAM-G2-SG02",
      "nb_menages": 88,
      "equipe_affectee": "Éq.Int-11",
      "centroide_lat": 13.393661,
      "centroide_lon": -13.706466
    },
    {
      "id": "TAM-G2-SG03",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 3,
      "nom": "Tambacounda – Grappe 2 – SG03",
      "code": "TAM-G2-SG03",
      "nb_menages": 86,
      "equipe_affectee": "Éq.Int-12",
      "centroide_lat": 13.469283,
      "centroide_lon": -13.712293
    },
    {
      "id": "TAM-G2-SG04",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 4,
      "nom": "Tambacounda – Grappe 2 – SG04",
      "code": "TAM-G2-SG04",
      "nb_menages": 81,
      "equipe_affectee": "Éq.Int-13",
      "centroide_lat": 13.420528,
      "centroide_lon": -13.68553
    },
    {
      "id": "TAM-G2-SG05",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 5,
      "nom": "Tambacounda – Grappe 2 – SG05",
      "code": "TAM-G2-SG05",
      "nb_menages": 70,
      "equipe_affectee": "Éq.Int-14",
      "centroide_lat": 13.474455,
      "centroide_lon": -13.652662
    },
    {
      "id": "TAM-G2-SG06",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 6,
      "nom": "Tambacounda – Grappe 2 – SG06",
      "code": "TAM-G2-SG06",
      "nb_menages": 63,
      "equipe_affectee": "Éq.Int-15",
      "centroide_lat": 13.425399,
      "centroide_lon": -13.666405
    },
    {
      "id": "TAM-G2-SG07",
      "grappe_id": "TAM-G2",
      "region": "Tambacounda",
      "grappe_numero": 2,
      "sous_grappe_numero": 7,
      "nom": "Tambacounda – Grappe 2 – SG07",
      "code": "TAM-G2-SG07",
      "nb_menages": 53,
      "equipe_affectee": "Éq.Int-16",
      "centroide_lat": 13.457738,
      "centroide_lon": -13.688792
    }
  ]
};
if (typeof window !== 'undefined') window.GRAPPES_CONFIG = GRAPPES_CONFIG;
if (typeof module !== 'undefined') module.exports = GRAPPES_CONFIG;
