/**
 * Configuration des Rôles et Permissions - PROQUELEC SaaS
 * Centralisation de la logique d'accès pour une maintenance facilitée.
 */

export const ROLES = {
    ADMIN: "ADMIN_PROQUELEC",
    ADMIN_ALT: "ADMINISTRATEUR",
    DG: "DG_PROQUELEC",
    DG_ALT: "DIRECTION GÉNÉRALE",
    CHEF_EQUIPE: "CHEF_EQUIPE",
    CHEF: "CHEF",
    CHEF_CHANTIER: "CHEF DE CHANTIER",
    CLIENT_LSE: "CLIENT_LSE",
    CHEF_PROJET: "CHEF DE PROJET",
    CHEF_PROJET_ALT: "CHEF_PROJET",
    COMPTABLE: "COMPTABLE",
    DIRECTEUR: "DIRECTEUR"
};

export const PERMISSIONS = {
    GERER_UTILISATEURS: "gerer_utilisateurs",
    GERER_PARAMETRES: "gerer_parametres",
    VOIR_DIAGNOSTIC: "voir_diagnostic",
    VOIR_FINANCES: "voir_finances",
    GERER_FINANCES: "gerer_finances",
    VOIR_SIMULATION: "voir_simulation",
    LANCER_SIMULATION: "lancer_simulation",
    VOIR_CARTE: "voir_carte",
    MODIFIER_CARTE: "modifier_carte",
    CREER_PROJET: "creer_projet",
    SUPPRIMER_PROJET: "supprimer_projet",
    GERER_LOGISTIQUE: "gerer_logistique",
    VOIR_RAPPORTS: "voir_rapports",
    ACCES_TERMINAL_KOBO: "acces_terminal_kobo",
    CREER_MISSION: "creer_mission",
    VALIDER_MISSION: "valider_mission",
    GERER_PV: "gerer_pv"
};

export const ROLE_PERMISSIONS = {
    // 👑 ADMIN: Accès absolu
    [ROLES.ADMIN]: Object.values(PERMISSIONS),
    [ROLES.ADMIN_ALT]: Object.values(PERMISSIONS),

    // 🚀 OPÉRATIONNELS: Tout sauf suppression de projet (peuvent créer)
    [ROLES.CHEF_PROJET]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.MODIFIER_CARTE,
        PERMISSIONS.CREER_PROJET,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV
    ],
    [ROLES.CHEF_PROJET_ALT]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.MODIFIER_CARTE,
        PERMISSIONS.CREER_PROJET,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV
    ],
    [ROLES.DIRECTEUR]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.MODIFIER_CARTE,
        PERMISSIONS.CREER_PROJET,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV
    ],

    // 📈 FINANCES & STRATÉGIE (DG & Comptable)
    [ROLES.DG]: [
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VALIDER_MISSION,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV
    ],
    [ROLES.DG_ALT]: [
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VALIDER_MISSION,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV
    ],
    [ROLES.COMPTABLE]: [
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.GERER_LOGISTIQUE
    ],

    // 🗺️ CLIENTS (LSE, etc.)
    [ROLES.CLIENT_LSE]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS
    ],

    // 🔨 ENTREPRENEURS EXTERIEURS (Chef de Chantier, Maçons, etc.)
    [ROLES.CHEF_CHANTIER]: [
        PERMISSIONS.ACCES_TERMINAL_KOBO
    ],
    [ROLES.CHEF]: [
        PERMISSIONS.ACCES_TERMINAL_KOBO
    ],
    [ROLES.CHEF_EQUIPE]: [
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS
    ]
};
