/**
 * Configuration des Rôles et Permissions - PROQUELEC SaaS
 * Centralisation de la logique d'accès pour une maintenance facilitée.
 */

export const ROLES = {
    ADMIN: "ADMIN_PROQUELEC",
    DIRECTEUR: "DIRECTEUR",
    CHEF_PROJET: "CHEF_PROJET",
    COMPTABLE: "COMPTABLE",
    CHEF_EQUIPE: "CHEF_EQUIPE",
    PATRIMOINE: "PATRIMOINE",
    EMPLOYE: "EMPLOYE",
    CLIENT_LSE: "CLIENT_LSE",
    SUPERVISEUR: "SUPERVISEUR",
    CONTROLEUR: "CONTROLEUR"
};

export const PERMISSIONS = {
    GERER_UTILISATEURS: "gerer_utilisateurs",
    GERER_PARAMETRES: "gerer_parametres",
    VOIR_DIAGNOSTIC: "voir_diagnostic",
    VOIR_FINANCES: "voir_finances",
    GERER_FINANCES: "gerer_finances",
    VOIR_SIMULATION: "voir_simulation",
    LANCER_SIMULATION: "lancer_simulation",
    VOIR_CARTE: "voir_carte",
    MODIFIER_CARTE: "modifier_carte",
    CREER_PROJET: "creer_projet",
    SUPPRIMER_PROJET: "supprimer_projet",
    GERER_LOGISTIQUE: "gerer_logistique",
    VOIR_RAPPORTS: "voir_rapports",
    ACCES_TERMINAL_KOBO: "acces_terminal_kobo",
    CREER_MISSION: "creer_mission",
    VALIDER_MISSION: "valider_mission",
    GERER_PV: "gerer_pv"
    ,
    // Permissions additionnelles pour l'UI granularité des missions
    VOIR_MISSIONS: "voir_missions",
    VOIR_REGISTRE_MISSIONS: "voir_registre_missions",
    MODIFIER_MISSIONS: "modifier_missions",
    SUPPRIMER_MISSIONS: "supprimer_missions",
    ARCHIVER_MISSIONS: "archiver_missions",
    VALIDATION_OPERATIONNELLE: "validation_operationnelle",
    APPROBATION_FINALE_DG: "approbation_finale_dg"
};

export const ROLE_PERMISSIONS = {
    // 👑 ADMIN: Accès absolu
    [ROLES.ADMIN]: Object.values(PERMISSIONS),
    [ROLES.ADMIN_ALT]: Object.values(PERMISSIONS),

    // 🚀 OPÉRATIONNELS: Tout sauf suppression de projet (peuvent créer)
    [ROLES.CHEF_PROJET]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.MODIFIER_CARTE,
        PERMISSIONS.CREER_PROJET,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV,
        PERMISSIONS.VOIR_MISSIONS,
        PERMISSIONS.MODIFIER_MISSIONS
    ],
    [ROLES.DIRECTEUR]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.MODIFIER_CARTE,
        PERMISSIONS.CREER_PROJET,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.VOIR_SIMULATION,
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.GERER_PV,
        PERMISSIONS.VALIDER_MISSION,
        PERMISSIONS.APPROBATION_FINALE_DG,
        PERMISSIONS.VOIR_MISSIONS,
        PERMISSIONS.MODIFIER_MISSIONS
    ],

    // 📈 FINANCES & AUDIT
    [ROLES.COMPTABLE]: [
        PERMISSIONS.VOIR_FINANCES,
        PERMISSIONS.GERER_FINANCES,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.CREER_MISSION,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_MISSIONS
    ],

    // 🗺️ CLIENTS & SUPERVISION EXTERNE
    [ROLES.CLIENT_LSE]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_MISSIONS
    ],
    [ROLES.SUPERVISEUR]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_MISSIONS,
        PERMISSIONS.VALIDER_MISSION
    ],
    [ROLES.CONTROLEUR]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_MISSIONS
    ],

    // 🔨 TERRAIN
    [ROLES.CHEF_EQUIPE]: [
        PERMISSIONS.ACCES_TERMINAL_KOBO,
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_MISSIONS,
        PERMISSIONS.VOIR_REGISTRE_MISSIONS
    ],
    [ROLES.EMPLOYE]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.VOIR_RAPPORTS,
        PERMISSIONS.VOIR_MISSIONS
    ],
    [ROLES.PATRIMOINE]: [
        PERMISSIONS.VOIR_CARTE,
        PERMISSIONS.GERER_LOGISTIQUE,
        PERMISSIONS.VOIR_MISSIONS
    ]
};
